FROM ghcr.io/cross-rs/aarch64-unknown-linux-musl:latest

RUN dpkg --add-architecture arm64 && \
    apt-get update 
    
RUN curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v22.2/protoc-22.2-linux-x86_64.zip && \
        unzip protoc-22.2-linux-x86_64.zip -d $HOME/.local && \
        export PATH="$PATH:$HOME/.local/bin"

